### ISSUE TITLE
where'd it go?

### ISSUE THREAD

**Issue by katieannemills** [lmguzman/ggplotVslattice#1]
Hi Melissa - I'd love to share your awesome ggplot/lattice lesson with Study Groups around the world, but I see there's nothing in this repo; let me know if we can get this material posted somewhere, wherever is convenient for you. Thanks again for the lesson yesterday!

**Comment by lmguzman** [comment]
Hey Bill, im sorry for replying so late, yeah im trying to get it up here. Ill be up in a bit :)

**Comment by lmguzman** [comment]
Done :D

**Comment by lmguzman** [comment]
Im not sure why its not showing the plots :S
