### ISSUE TITLE
File too big?

### ISSUE THREAD

**Issue by lmguzman** [lmguzman/ggplotVslattice#2]
@BillMills hey its telling me the html is too large so its truncating it. I deleted a bunch of plots and it still does the same. Do you have any suggestion?

**Comment by katieannemills** [comment]
As far as I can tell, this is a design decision from Rstudio or Knittr (not sure who exactly :); they really wanted to make the _whole document_ just one file, so all the image data etc gets encoded as those giant strings.

I would commit the images as pngs (or whatever) to the repo, perhaps in an `img/` directory, and add them to the markdown directly (`![Alt text](/path/to/img.png)`). Then, you don't even really need the html at all.

**Comment by jbkunst** [comment]
Hi,

In your yaml configuration (the header of the rmarkdown file) try the nexts lines:

```
output:
  html_document:
    self_contained: no
```

This should generate images files instead write of `<img src="data:image/png;base64,iV big lines of  encode images BORw0KGgoAAAANSUhE ..........>` in the html.

Regards,

**Comment by lmguzman** [comment]
Ok, fixed, thank you!
