### ISSUE TITLE
Other differences

### ISSUE THREAD

**Issue by jbkunst** [lmguzman/ggplotVslattice#3]
Hi Melissa!

Nice lesson! Other main differences can be:
1. The way you write the code: In lattice al the parameters/specification are in _one_ function instead ggplots which use layers: This make easy the debugging when you have an error and you don't know what is wrong.
2. The visual customization. In ggplot is relative easy create new themes (see [ggthemes](https://github.com/jrnold/ggthemes)).

Regards,

Joshua (A ggplot lover? :smile:)

https://rawgit.com/lmguzman/ggplotVslattice/master/Lesson1.html

**Comment by lmguzman** [comment]
Thank you!! :)
